/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.3.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as common from "../common";
import type * as createGame from "../createGame";
import type * as createOrJoinRandom from "../createOrJoinRandom";
import type * as createRound from "../createRound";
import type * as guessWord from "../guessWord";
import type * as joinGame from "../joinGame";
import type * as leaveGame from "../leaveGame";
import type * as lib_withUser from "../lib/withUser";
import type * as ping from "../ping";
import type * as purgeAbandoned from "../purgeAbandoned";
import type * as queryGame from "../queryGame";
import type * as queryRound from "../queryRound";
import type * as spy from "../spy";
import type * as storeUser from "../storeUser";
import type * as updateName from "../updateName";
import type * as validateGame from "../validateGame";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  common: typeof common;
  createGame: typeof createGame;
  createOrJoinRandom: typeof createOrJoinRandom;
  createRound: typeof createRound;
  guessWord: typeof guessWord;
  joinGame: typeof joinGame;
  leaveGame: typeof leaveGame;
  "lib/withUser": typeof lib_withUser;
  ping: typeof ping;
  purgeAbandoned: typeof purgeAbandoned;
  queryGame: typeof queryGame;
  queryRound: typeof queryRound;
  spy: typeof spy;
  storeUser: typeof storeUser;
  updateName: typeof updateName;
  validateGame: typeof validateGame;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
