# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Abandon Idle Games
on:
  schedule:
    - cron: '* * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
    - run: npm ci
    - name: Run idle game purge
      run: npm run purge
      env:
        CONVEX_ADMIN_KEY: ${{ secrets.CONVEX_ADMIN_KEY }}
